const booths = [
  {
    id: 0,
    category: 'Clothing',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance - $400',
          'Moderate Dry Cleaning - $100',
        ],
        price: 500,
      },

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },

  {
    id: 1,
    category: 'Household Expenses',
    options: [
      {
        id: 0,
        name: 'BUNDLE SPECIAL',
        descTitle: 'Internet/TV/Home Phone',
        desc: ['200 Mbps', '125+ Channels', 'Voice Over', '2 Year Agreement'],
        costbreakdown: ['All Inclusive'],
        price: 140,
      },
      {
        id: 1,
        name: 'CELL PHONE',
        descTitle: 'Unlimited Data Plan',
        desc: [
          '15GB High-Speed Mobil Hot Spot Data Per Month',
          'Access to 5G Networks',
        ],
        costbreakdown: ['All Inclusive'],
        price: 85,
      },

      {
        id: 2,
        name: 'INTERNET',
        descTitle: '300 Mbps',
        desc: ['1 Year Agreement'],
        costbreakdown: ['All Inclusive'],
        price: 35,
      },
    ],
  },

  {
    id: 2,
    category: 'Transportation',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance: $400/month',
          'Moderate Dry Cleaning: $100/month',
        ],
        price: 500,
      },

      // Dummy

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },

  {
    id: 3,
    category: 'Charity',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance: $400/month',
          'Moderate Dry Cleaning: $100/month',
        ],
        price: 500,
      },

      // Dummy

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },

  {
    id: 4,
    category: 'Food & Activities',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance: $400/month',
          'Moderate Dry Cleaning: $100/month',
        ],
        price: 500,
      },

      // Dummy

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },

  {
    id: 5,
    category: 'Temptation Island',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance: $400/month',
          'Moderate Dry Cleaning: $100/month',
        ],
        price: 500,
      },

      // Dummy

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },

  {
    id: 6,
    category: 'Insurance',
    options: [
      {
        id: 0,
        name: 'DEPARTMENT STORES & HIGH END BOUTIQUES',
        desc: [
          'Belk',
          'Haddad’s',
          'Haneline’s Men’s Wear',
          'Dillard’s',
          'Stein Mart',
          'Talbots',
          'Chico’s',
          'Ron Alexander',
          'Signatures by Linda Reeves',
          'Joseph A Bank',
          'Her Toggery',
          'The Toggery',
          'The Cotton Patch',
        ],
        costbreakdown: [
          'Clothing Allowance: $400/month',
          'Moderate Dry Cleaning: $100/month',
        ],
        price: 500,
      },

      // Dummy

      {
        id: 1,
        name: 'MALL & OUTLET STORES',
        desc: [
          'Abercrombie & Fitch',
          'Aeropostale',
          'American Eagle',
          'Lane Bryant',
          'Burlington',
          'Charlotte Russe',
          'Express',
          'Hollister',
          'Buckle',
          'Old Navy',
          'Maurice’s',
          'New York & Company',
          'K-Sera',
          'Herringstones',
          'Kohl’s',
        ],
        costbreakdown: [
          'Clothing Allowance - $250',
          'Light Dry Cleaning - $50',
        ],
        price: 300,
      },

      {
        id: 2,
        name: 'DISCOUNT STORES',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $85', 'DIY Laundry - $15'],
        price: 100,
      },

      {
        id: 3,
        name: 'Thrift/Consignment Stores',
        desc: [
          'Cato',
          'Citi-Trends',
          'Burke’s Outlet',
          'Rainbow',
          'Ross Dress for Less',
          'Rue 21',
          'Simply Fashions',
          'Dirt Cheap',
          'Target',
          'Wal-Mart',
          'Fashion Cents',
          'Forever 21',
        ],
        costbreakdown: ['Clothing Allowance - $15', 'DIY Laundry - $15'],
        price: 30,
      },
    ],
  },
];

const education = [
  'High School Diploma',
  'Bachelors Degree',
  'Masters Degree',
  'GED/HSET',
  'Asscoiates Degree',
  'PhD',
];

const calculationInfo = [{ totalhoursworked: 2080 }];

const jobs = [
  {
    reqed: 'HighSchool Diploma',
    occupations: [
      { id: 0, position: 'Welder', grossmonthly: 3234.4 },
      { id: 1, position: 'Plumber', grossmonthly: 3731.87 },
      { id: 2, position: 'Truck Driver', grossmonthly: 3194.53 },
      { id: 3, position: 'Carpenter', grossmonthly: 2594.8 },
    ],
  },

  {
    reqed: 'Bachelors Degree',
    occupations: [
      { id: 0, position: 'Accountant', grossmonthly: 5395.87 },
      { id: 1, position: 'Electrical Engineer', grossmonthly: 4943.47 },
      { id: 2, position: 'Social Worker', grossmonthly: 3156.4 },
      { id: 3, position: 'Toxocologist', grossmonthly: 4745.53 },
    ],
  },

  { reqed: 'Associates Degree', occupations: [] },

  { reqed: 'Masters Degree', occupations: [] },

  { reqed: 'PhD', occupations: [] },

  { reqed: 'GED/HSET', occupations: [] },
];

export { jobs, calculationInfo, booths, education };
